### ISSUE TITLE
comenzar en programacion.

### ISSUE THREAD

**Issue by matepirola** [za0sec/Programacion-Imperativa#2]
hola za0sec, viendo que sos un gran exponente en el mundo de la programacion, con cual lenguaje me recomendarias empezar? Espero con ansias tu respuesta.

SALUDOS, mateo.

**Comment by za0sec** [comment]
Hola Mateo! Creo que una gran parte de mi aprendizaje fue en el lenguaje C. Siendo este el que te ensena a manejar memoria y entender como funciona la computadora.
Si necesitas ayuda consultame!

**Comment by matepirola** [comment]
muchas gracias! Espero alguna vez estar tu nivel de programacion. saludos
